"""Tests deterministes du garde-fou A2 (commentaires synthetiques, aucun reseau)."""
import importlib.util
from datetime import datetime, timezone
import pathlib
import unittest

spec = importlib.util.spec_from_file_location("wd", pathlib.Path(__file__).with_name("a2_watchdog.py"))
wd = importlib.util.module_from_spec(spec)
spec.loader.exec_module(wd)
NOW = datetime(2026, 10, 8, 12, 0, tzinfo=timezone.utc)


def c(cid, at, sender, target, extra="", demande="faire x"):
    login = wd.CODEX_LOGIN if sender == "orchestrateur" else wd.OWNER_LOGIN
    footer = "\n---\n_Generated by [Claude Code](https://claude.ai/code)_" if sender != "orchestrateur" else ""
    return {"id": cid, "created_at": f"2026-10-08T{at}:00Z", "user": {"login": login},
            "body": f"[A2-TEAM] DE: {sender} → À: {target}\nOBJET: x\nDEMANDE: {demande}\n{extra}{footer}"}


def owner(cid, at, text):
    return {"id": cid, "created_at": f"2026-10-08T{at}:00Z", "user": {"login": wd.OWNER_LOGIN}, "body": text}


def watchdog(cid, at, text):
    return {"id": cid, "created_at": f"2026-10-08T{at}:00Z", "user": {"login": wd.OWNER_LOGIN},
            "body": f"[A2-TEAM] DE: watchdog → À: orchestrateur\nOBJET: {text}\n---\n_Generated by [Claude Code](https://claude.ai/code)_"}


class Watchdog(unittest.TestCase):
    def test_overdue_wait_on_codex_pings_codex_once_with_key(self):
        a = wd.evaluate([c(1, "08:00", "builder", "orchestrateur", "ATTENTE[A1]: arbitrage avant 2026-10-08T09:00Z")], NOW, False)
        self.assertEqual(len(a), 1)
        self.assertIn("PING_CODEX", a[0])
        self.assertIn("[cle=PING:orchestrateur:1:A1]", a[0])

    def test_reminder_not_repeated_then_escalates_once(self):
        base = [c(1, "08:00", "builder", "orchestrateur", "ATTENTE[A1]: x avant 2026-10-08T09:00Z")]
        pinged = base + [watchdog(2, "09:39", "RAPPEL watchdog PING:orchestrateur:1:A1")]
        a = wd.evaluate(pinged, NOW, False)
        self.assertEqual(len(a), 1)
        self.assertIn("ALERT_OWNER", a[0])
        alerted = pinged + [watchdog(3, "11:39", "ALERT_OWNER watchdog ALERT:orchestrateur:1:A1")]
        self.assertEqual(wd.evaluate(alerted, NOW, False), [])

    def test_unrelated_reply_does_not_close_an_id_wait(self):
        a = wd.evaluate([c(1, "08:00", "builder", "orchestrateur", "ATTENTE[A1]: x avant 2026-10-08T09:00Z"),
                         c(2, "08:30", "orchestrateur", "builder", demande="aucune")], NOW, False)
        self.assertEqual(len(a), 1)
        self.assertIn("PING_CODEX", a[0])

    def test_sender_can_close_a_wait_with_clos_marker_in_the_queue(self):
        base = [c(1, "08:00", "builder", "orchestrateur", "ATTENTE[A1]: x avant 2026-10-08T09:00Z"),
                c(2, "08:30", "orchestrateur", "builder", demande="aucune")]
        self.assertEqual(len(wd.evaluate(base, NOW, False)), 1)
        self.assertEqual(wd.evaluate(base, NOW, False, wd.closed_ids_in("| X | CLOS[A1@1] reponse 2 |")), [])
        self.assertEqual(wd.closed_ids_in("CLOS[S1@11] et CLOS[S3@33] mais pas CLOS[S9] ni CLOSED[S8@8]"), {("S1", "11"), ("S3", "33")})
        # un id reutilise dans une autre attente n'est pas clos
        other = [c(5, "08:00", "builder", "orchestrateur", "ATTENTE[A1]: y avant 2026-10-08T09:00Z")]
        self.assertEqual(len(wd.evaluate(other, NOW, False, wd.closed_ids_in("CLOS[A1@1]"))), 1)

    def test_reply_citing_the_id_closes_the_wait(self):
        a = wd.evaluate([c(1, "08:00", "builder", "orchestrateur", "ATTENTE[A1]: x avant 2026-10-08T09:00Z"),
                         c(2, "08:30", "orchestrateur", "builder", "REF A1", demande="aucune")], NOW, False)
        self.assertEqual(a, [])

    def test_an_unrelated_longer_id_or_a_sha_substring_does_not_close_the_wait(self):
        wait = c(1, "08:00", "builder", "orchestrateur", "ATTENTE[C9]: x avant 2026-10-08T09:00Z")
        for text in ("a propos de C90", "sha 0ac9f1 et XC9", "C9x", "C9-bis"):
            a = wd.evaluate([wait, c(2, "08:30", "orchestrateur", "builder", text, demande="aucune")], NOW, False)
            self.assertEqual(len(a), 1, text)
        for text in ("CLOS[C9@1]", "voir C9.", "(C9)", "C9, merci"):
            a = wd.evaluate([wait, c(2, "08:30", "orchestrateur", "builder", text, demande="aucune")], NOW, False)
            self.assertEqual(a, [], text)

    def test_legacy_wait_without_id_closed_by_any_later_message(self):
        a = wd.evaluate([c(1, "08:00", "builder", "orchestrateur", "ATTENTE: x avant 2026-10-08T09:00Z"),
                         c(2, "08:30", "orchestrateur", "builder", demande="aucune")], NOW, False)
        self.assertEqual(a, [])

    def test_wait_not_yet_due_is_silent(self):
        self.assertEqual(wd.evaluate([c(1, "11:30", "builder", "orchestrateur", "ATTENTE[A]: x avant 2026-10-08T13:00Z")], NOW, False), [])

    def test_overdue_wait_on_builder_wakes_builder(self):
        a = wd.evaluate([c(1, "08:00", "orchestrateur", "builder", "ATTENTE[B]: x avant 2026-10-08T09:00Z")], NOW, False)
        self.assertEqual(len(a), 1)
        self.assertIn("WAKE_BUILDER", a[0])

    def test_unanswered_request_without_deadline_after_15_min(self):
        self.assertTrue(any("PING_CODEX" in x for x in wd.evaluate([c(1, "11:40", "builder", "orchestrateur")], NOW, False)))
        self.assertEqual(wd.evaluate([c(1, "11:50", "builder", "orchestrateur")], NOW, False), [])

    def test_reply_with_no_request_does_not_wake_the_other_side(self):
        a = wd.evaluate([c(1, "11:00", "builder", "orchestrateur"), c(2, "11:10", "orchestrateur", "builder", demande="aucune")], NOW, False)
        self.assertFalse(any("WAKE_BUILDER" in x for x in a))

    def test_team_silent_alert_once_per_last_message(self):
        quiet = [c(1, "10:00", "builder", "orchestrateur"), c(2, "10:10", "orchestrateur", "builder", demande="aucune")]
        a = wd.evaluate(quiet, NOW, True)
        self.assertTrue(any("ALERT:team:2" in x for x in a))
        self.assertFalse(any("ALERT_OWNER" in x for x in wd.evaluate(quiet, NOW, False)))
        again = quiet + [watchdog(3, "11:30", "ALERT_OWNER watchdog ALERT:team:2")]
        self.assertFalse(any("ALERT:team:2" in x for x in wd.evaluate(again, NOW, True)))

    def test_owner_stop_silences_everything_until_resume(self):
        base = [c(1, "08:00", "builder", "orchestrateur", "ATTENTE[A1]: x avant 2026-10-08T09:00Z")]
        self.assertEqual(wd.evaluate(base + [owner(5, "10:00", "STOP")], NOW, True), [])
        self.assertTrue(wd.evaluate(base + [owner(5, "10:00", "STOP"), owner(6, "10:30", "REPRISE")], NOW, True))
        self.assertTrue(wd.evaluate(base + [{"id": 7, "created_at": "2026-10-08T10:00:00Z", "user": {"login": "someone"}, "body": "STOP"}], NOW, True))

    def test_spoofed_headers_and_markers_from_other_accounts_are_ignored(self):
        spoof = {"id": 1, "created_at": "2026-10-08T08:00:00Z", "user": {"login": "intrus"},
                 "body": "[A2-TEAM] DE: builder → À: orchestrateur\nDEMANDE: x\nATTENTE[Z]: x avant 2026-10-08T09:00Z\n_Generated by [Claude Code]_"}
        self.assertEqual(wd.evaluate([spoof], NOW, False), [])
        base = [c(1, "08:00", "builder", "orchestrateur", "ATTENTE[A1]: x avant 2026-10-08T09:00Z")]
        fake_reply = {"id": 2, "created_at": "2026-10-08T08:30:00Z", "user": {"login": "intrus"},
                      "body": "[A2-TEAM] DE: orchestrateur → À: builder\nDEMANDE: aucune\nA1"}
        self.assertEqual(len(wd.evaluate(base + [fake_reply], NOW, False)), 1)  # la fausse reponse ne clot rien
        fake_marker = {"id": 3, "created_at": "2026-10-08T09:30:00Z", "user": {"login": "intrus"},
                       "body": "[A2-TEAM] DE: watchdog → À: orchestrateur\nOBJET: RAPPEL watchdog PING:orchestrateur:1:A1\n_Generated by [Claude Code]_"}
        a = wd.evaluate(base + [fake_marker], NOW, False)
        self.assertEqual(len(a), 1)
        self.assertIn("PING_CODEX", a[0])  # le faux marqueur ne supprime pas le rappel
        no_footer = dict(c(4, "08:00", "builder", "orchestrateur"))
        no_footer["body"] = no_footer["body"].split("\n---")[0]
        self.assertEqual(wd.messages([no_footer]), [])

    def test_flatten_pages(self):
        self.assertEqual(wd.flatten_pages([[1, 2], [3]]), [1, 2, 3])
        self.assertEqual(wd.flatten_pages([{"id": 1}, {"id": 2}]), [{"id": 1}, {"id": 2}])
        self.assertEqual(wd.flatten_pages([]), [])

    def test_non_team_and_malformed_comments_are_ignored(self):
        junk = [{"id": 1, "created_at": "2026-10-08T01:00:00Z", "user": {"login": "x"}, "body": "Je ratifie"},
                {"id": 2, "created_at": "2026-10-08T01:00:00Z", "user": {"login": "x"},
                 "body": "[A2-TEAM] DE: owner → À: builder\nATTENTE: x avant 2026-10-08T02:00Z"}]
        self.assertEqual(wd.evaluate(junk, NOW, False), [])

    def test_ascii_arrow_and_two_targets(self):
        body = {"id": 9, "created_at": "2026-10-08T06:00:00Z", "user": {"login": wd.CODEX_LOGIN},
                "body": "[A2-TEAM] DE: orchestrateur -> A: Owner, builder\nATTENTE[Z]: avis avant 2026-10-08T07:00Z"}
        a = wd.evaluate([body], NOW, False)
        self.assertEqual(len(a), 1)
        self.assertIn("WAKE_BUILDER", a[0])

    def test_open_work_detection(self):
        self.assertTrue(wd.open_work_in("| Q1 | x | READY |"))
        self.assertFalse(wd.open_work_in("| Q1 | x | DONE |\n| Q2 | y | OWNER_GATED |\n| Q3 | z | BLOCKED |"))
        self.assertFalse(wd.open_work_in("| C2 | x | GELÉ (B3, réversible) |\n| Q1 | y | DONE : `abc` |"))
        self.assertTrue(wd.open_work_in("| C2 | x | GELÉ |\n| B2 | y | READY |"))
        # un mot de statut dans une autre cellule ne masque pas une tache ouverte
        self.assertTrue(wd.open_work_in("| Q9 | attend DONE de Q1 | IN_PROGRESS |"))


if __name__ == "__main__":
    unittest.main()
