"""Tests du compteur d'equilibre du script d'etat d'equipe (commentaires synthetiques, aucun reseau)."""
import importlib.util
import pathlib
import unittest
from datetime import datetime, timezone

spec = importlib.util.spec_from_file_location("st", pathlib.Path(__file__).with_name("a2_team_status.py"))
st = importlib.util.module_from_spec(spec)
spec.loader.exec_module(st)

CUTOFF = datetime(2026, 10, 8, 0, 0, tzinfo=timezone.utc)
FOOT = "\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


def c(sender, login, at="10:00", footer=True):
    body = f"[A2-TEAM] DE: {sender} → À: x\nOBJET: y" + (FOOT if footer else "")
    return {"created_at": f"2026-10-08T{at}:00Z", "user": {"login": login}, "body": body}


class Balance(unittest.TestCase):
    def test_authentic_messages_are_counted(self):
        comments = [c("builder", st.OWNER_LOGIN), c("orchestrateur", st.CODEX_LOGIN, footer=False)]
        self.assertEqual(st.count_messages(comments, CUTOFF), {"builder": 1, "orchestrateur": 1})

    def test_forged_headers_are_ignored(self):
        comments = [c("builder", "someone-else"), c("orchestrateur", "someone-else", footer=False),
                    c("builder", st.OWNER_LOGIN, footer=False),            # sans pied de page Claude Code
                    c("orchestrateur", st.OWNER_LOGIN, footer=False)]       # le depot ne parle pas au nom de Codex
        self.assertEqual(st.count_messages(comments, CUTOFF), {"builder": 0, "orchestrateur": 0})

    def test_old_messages_and_other_senders_are_ignored(self):
        old = c("builder", st.OWNER_LOGIN)
        old["created_at"] = "2026-10-07T10:00:00Z"
        other = c("astra", st.OWNER_LOGIN)
        self.assertEqual(st.count_messages([old, other, {"body": "no header", "user": None, "created_at": "2026-10-08T10:00:00Z"}], CUTOFF),
                         {"builder": 0, "orchestrateur": 0})


class Flag(unittest.TestCase):
    def test_either_agent_leading_above_60_percent_is_named(self):
        self.assertIn("le Builder mene", st.balance_flag(61))
        self.assertIn("l'orchestrateur mene", st.balance_flag(39))
        self.assertIn("l'orchestrateur mene", st.balance_flag(0))
        self.assertIn("le Builder mene", st.balance_flag(100))

    def test_balanced_split_has_no_flag(self):
        for share in (40, 50, 60):
            self.assertEqual(st.balance_flag(share), "")


if __name__ == "__main__":
    unittest.main()
