"""Rebuild and verify committed V1 status artifacts from canonical persistent state.

The live ``var/`` directory is intentionally git-ignored.  Committed status artifacts therefore
need a reproducible source of truth that does not depend on one operator's machine.  This script
reconstructs a clean persistent V1 state from the committed datasets and opportunity map, runs the
real Control Plane to IDLE, and renders the status facts from that persisted state.

Use ``--write`` at a meaningful milestone and ``--check`` in CI.  The check is deliberately
substantive: ``CHIEF_BRIEF.md`` is regenerated in full and the generated checkpoint in
``STATE.md`` is replaced from the same snapshot before comparison.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import re
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from quant.clock import QuantSystem  # noqa: E402
from quant.dataplane.ingest import register_committed_snapshots  # noqa: E402
from quant.dataplane.registry import DatasetRegistry  # noqa: E402
from quant.events import EventLog  # noqa: E402
from quant.paths import QuantPaths  # noqa: E402
from quant.status.brief import build_chief_brief  # noqa: E402

STATE_START = "<!-- BEGIN GENERATED CANONICAL V1 STATUS -->"
STATE_END = "<!-- END GENERATED CANONICAL V1 STATUS -->"


def canonical_snapshot() -> dict[str, Any]:
    """Reconstruct the canonical V1 state from committed inputs and run it to IDLE."""
    with tempfile.TemporaryDirectory(prefix="quant-v1-canonical-status-") as directory:
        root = Path(directory)
        (root / "data").mkdir()
        (root / "research").mkdir()
        shutil.copytree(ROOT / "data" / "datasets", root / "data" / "datasets")
        shutil.copy2(ROOT / "research" / "opportunity_map.json", root / "research")

        paths = QuantPaths(root).ensure()
        registry = DatasetRegistry(paths.dataset_registry, root)
        log = EventLog(paths.events)
        registered = register_committed_snapshots(paths, registry, log)
        if not registered or not registry.health()["healthy"]:
            raise RuntimeError("committed datasets did not reconstruct a healthy canonical registry")

        system = QuantSystem(root)
        system.boot()
        system.run()
        snapshot = system.snapshot()
        if snapshot["health"]:
            raise RuntimeError(f"canonical replay ended unhealthy: {snapshot['health']}")
        if snapshot["control"]["status"] != "IDLE":
            raise RuntimeError(f"canonical replay did not reach IDLE: {snapshot['control']['status']}")
        return snapshot


def unit_test_count() -> int:
    """Count exactly what unittest discovery sees without executing the suite."""
    suite = unittest.TestLoader().discover(str(ROOT / "tests"), pattern="test*.py")
    return suite.countTestCases()


def demo_assertion_count() -> int:
    """Count declared end-to-end ``check(...)`` assertions in the demo source."""
    tree = ast.parse((ROOT / "scripts" / "demo_quant_system.py").read_text(encoding="utf-8"))
    return sum(
        1
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id == "check"
    )


def canonical_brief(snapshot: dict[str, Any]) -> str:
    """Render the Chief Brief with deterministic provenance instead of wall-clock generation time."""
    brief = build_chief_brief(snapshot)
    last_session = snapshot["book"]["last_session_date"]
    replacement = (
        "- canonical state basis: clean persistent replay of committed inputs "
        f"through {last_session}"
    )
    brief, substitutions = re.subn(
        r"^- generated at: .+$", replacement, brief, count=1, flags=re.MULTILINE
    )
    if substitutions != 1:
        raise RuntimeError("Chief Brief generation timestamp marker was not found")
    return brief


def state_checkpoint(snapshot: dict[str, Any], tests: int, demo_checks: int) -> str:
    control = snapshot["control"]
    book = snapshot["book"]
    evaluation = snapshot["evaluation"]
    tickets = snapshot["tickets"]["by_status"]
    queue = snapshot["research"]["queue"]
    data_health = snapshot["data"]["health"]["by_availability"]
    quality = snapshot["learning"]["decision_quality"]

    return "\n".join([
        STATE_START,
        "## Canonical V1 status checkpoint",
        "",
        "This block is generated by `python3 scripts/status_artifacts.py --write` from a clean",
        "persistent replay of the committed V1 inputs. CI reconstructs the same state and fails if",
        "either this checkpoint or `CHIEF_BRIEF.md` drifts from it.",
        "",
        f"- Proof inventory: **{tests} unit tests discovered**; **{demo_checks} end-to-end demo assertions**.",
        f"- Control/Desk: status **{control['status']}**, desk cursor `{control['desk_cursor']}`, "
        f"**{control['desk_sessions']} executable desk sessions**.",
        f"- Data Plane: `{data_health}`.",
        f"- Research queue: `{queue}`.",
        f"- Capital Book: NAV **{book['nav']:,.2f} {book['currency']}**, **{book['sessions']}** marked "
        f"sessions, **{book['fills']}** fills, **{book['open_positions']}** open positions; last mark "
        f"`{book['last_session_date']}`.",
        f"- Evaluation ledger (zero authority): NAV **{evaluation['nav']:,.2f}** "
        f"({evaluation['total_return']:+.2%}) over **{evaluation['sessions']}** sessions; "
        f"counterfactual P&L **{quality.get('counterfactual_pnl', 0.0):,.2f}**.",
        f"- Desk tickets: `{tickets}`.",
        f"- Rejection quality: **{quality.get('strategies_evaluated', 0)}** evaluated, "
        f"**{quality.get('true_rejects', 0)}** true rejects, "
        f"**{quality.get('false_rejects', 0)}** false rejects, "
        f"**{quality.get('undetermined', 0)}** undetermined.",
        STATE_END,
    ])


def reconcile_state(text: str, block: str) -> str:
    if STATE_START in text or STATE_END in text:
        if text.count(STATE_START) != 1 or text.count(STATE_END) != 1:
            raise RuntimeError("STATE.md has malformed canonical-status markers")
        before, tail = text.split(STATE_START, 1)
        _, after = tail.split(STATE_END, 1)
        return before + block + after

    anchor = "## Architectural state"
    if anchor not in text:
        raise RuntimeError("STATE.md architectural anchor not found")
    return text.replace(anchor, block + "\n\n" + anchor, 1)


def expected_artifacts() -> dict[Path, str]:
    snapshot = canonical_snapshot()
    tests = unit_test_count()
    demo_checks = demo_assertion_count()
    state_path = ROOT / "STATE.md"
    return {
        ROOT / "CHIEF_BRIEF.md": canonical_brief(snapshot),
        state_path: reconcile_state(
            state_path.read_text(encoding="utf-8"),
            state_checkpoint(snapshot, tests, demo_checks),
        ),
    }


def write_artifacts() -> int:
    for path, expected in expected_artifacts().items():
        path.write_text(expected, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


def check_artifacts() -> int:
    stale = False
    for path, expected in expected_artifacts().items():
        actual = path.read_text(encoding="utf-8")
        if actual == expected:
            print(f"fresh: {path.relative_to(ROOT)}")
            continue
        stale = True
        print(f"STALE: {path.relative_to(ROOT)}")
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(path.relative_to(ROOT)),
            tofile=f"generated/{path.relative_to(ROOT)}",
            lineterm="",
        )
        print("\n".join(diff))
    return 1 if stale else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate committed status artifacts")
    mode.add_argument("--check", action="store_true", help="fail if committed status artifacts are stale")
    args = parser.parse_args()
    return write_artifacts() if args.write else check_artifacts()


if __name__ == "__main__":
    raise SystemExit(main())
