"""F1 receptions de livraison et historique des prix

Revision ID: 4abb02487349
Revises: ac56caeab83e
Create Date: 2026-09-02 13:56:43.540662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abb02487349'
down_revision: Union[str, None] = 'ac56caeab83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_on', sa.DateTime(), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_receipts_supplier'), ['supplier'], unique=False)

    op.create_table('delivery_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('previous_unit_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['delivery_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['delivery_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default indispensable : la table settings contient déjà une ligne
    # sur une base existante, une colonne NOT NULL sans défaut échouerait.
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('price_alert_pct', sa.Float(), nullable=False, server_default='15.0')
        )
    # Le défaut applicatif prend le relais pour les insertions suivantes.
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('price_alert_pct', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('price_alert_pct')

    op.drop_table('price_history')
    op.drop_table('delivery_lines')
    with op.batch_alter_table('delivery_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_receipts_supplier'))

    op.drop_table('delivery_receipts')
    # ### end Alembic commands ###
