"""F2 journal des erreurs

Revision ID: 45d4859fda91
Revises: 79dd843f278c
Create Date: 2026-09-02 14:12:23.217904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d4859fda91'
down_revision: Union[str, None] = '79dd843f278c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('error_type', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_occurred_at'), ['occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_occurred_at'))

    op.drop_table('error_logs')
    # ### end Alembic commands ###
