"""baseline_v1

Revision ID: ac56caeab83e
Revises: 
Create Date: 2026-09-02 13:37:39.290637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac56caeab83e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('counted_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dishes_name'), ['name'], unique=True)

    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.Enum('g', 'kg', 'mL', 'L', 'unité', name='unit'), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('storage_zone', sa.Enum('sec', 'frigo_positif', 'frigo_negatif', 'cave', name='storagezone'), nullable=False),
    sa.Column('current_theoretical_stock', sa.Float(), nullable=False),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_name'), ['name'], unique=True)

    op.create_table('order_suggestion_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('safety_days', sa.Float(), nullable=False),
    sa.Column('target_days', sa.Float(), nullable=False),
    sa.Column('rolling_window_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('count_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_session_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('theoretical_quantity', sa.Float(), nullable=False),
    sa.Column('counted_quantity', sa.Float(), nullable=True),
    sa.Column('variance_reason', sa.Enum('casse', 'perime', 'offert', 'erreur_saisie', 'autre', name='variancereason'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['count_session_id'], ['count_sessions.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=200), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dish_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dish_aliases_raw_name'), ['raw_name'], unique=True)

    op.create_table('order_suggestion_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('avg_daily_consumption', sa.Float(), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('suggested_quantity', sa.Float(), nullable=False),
    sa.Column('final_quantity', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('en_attente', 'acceptee', 'modifiee', 'rejetee', name='suggestiondecision'), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['order_suggestion_batches.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id', 'ingredient_id')
    )
    op.create_table('sale_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_import_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('raw_dish_name', sa.String(length=200), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('quantity_sold', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('stock_applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['sales_import_id'], ['sales_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('vente', 'comptage', 'ajustement', name='movementtype'), nullable=False),
    sa.Column('quantity_delta', sa.Float(), nullable=False),
    sa.Column('resulting_stock', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movements')
    op.drop_table('sale_lines')
    op.drop_table('recipe_ingredients')
    op.drop_table('order_suggestion_lines')
    with op.batch_alter_table('dish_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_aliases_raw_name'))

    op.drop_table('dish_aliases')
    op.drop_table('count_lines')
    op.drop_table('settings')
    op.drop_table('sales_imports')
    op.drop_table('order_suggestion_batches')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_name'))

    op.drop_table('ingredients')
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dishes_name'))

    op.drop_table('dishes')
    op.drop_table('count_sessions')
    # ### end Alembic commands ###
