"""Blind transport/recovery contracts on generated bytes, no network."""
import base64
import hashlib
import json
from pathlib import Path
import tempfile
import unittest

from capture import form_fields,check_provider_checksums,recover_file
from run import atomic_json


JOB={'expected_archive_name':'HISTDATA_COM_ASCII_EURUSD_T_202501.zip',
     'page_url':'https://www.histdata.com/download-free-forex-historical-data/?/ascii/tick-data-quotes/eurusd/2025/1',
     'post_fields':{'date':'2025','datemonth':'202501','platform':'ASCII','timeframe':'T','fxpair':'EURUSD'}}


class CaptureTests(unittest.TestCase):
    def test_free_form_exact_parameters_and_local_ephemeral_field(self):
        inputs=''.join('<input name="'+k+'" value="'+v+'" />' for k,v in {**JOB['post_fields'],'tk':'synthetic'}.items())
        page='<form id="file_down" method="POST" action="/get.php">'+inputs+'</form>'
        fields=form_fields(page,JOB)
        self.assertEqual(fields,{**JOB['post_fields'],'tk':'synthetic'})
        with self.assertRaises(ValueError):form_fields(page.replace('202501','202502'),JOB)
        with self.assertRaises(ValueError):form_fields(page.replace('/get.php','/pay.php'),JOB)
        with self.assertRaises(ValueError):form_fields(page.replace('</form>','<input name="account" value="x" /></form>'),JOB)

    def test_missing_provider_checksum_is_disclosed_not_invented(self):
        self.assertEqual(check_provider_checksums({},'a'*64,'b'*32),{'provider_sha256':None})

    def test_provider_hashes_verified_case_insensitively(self):
        b=b'synthetic compressed capture';sha=hashlib.sha256(b).hexdigest();md5=hashlib.md5(b).hexdigest()
        headers={'content-md5':base64.b64encode(bytes.fromhex(md5)).decode(),
                 'digest':'sha-256='+base64.b64encode(bytes.fromhex(sha)).decode()}
        proof=check_provider_checksums(headers,sha,md5)
        self.assertEqual(proof['provider_sha256'],sha)
        self.assertTrue(proof['content_md5_verified'])
        with self.assertRaises(ValueError):check_provider_checksums(headers,'a'*64,md5)

    def test_every_advertised_digest_is_checked_including_conflicts(self):
        b=b'synthetic';sha=hashlib.sha256(b).hexdigest();md5=hashlib.md5(b).hexdigest()
        h={'Content-Digest':'sha-256=:'+base64.b64encode(bytes.fromhex(sha)).decode()+':' }
        self.assertEqual(check_provider_checksums(h,sha,md5)['provider_sha256'],sha)
        with self.assertRaises(ValueError):check_provider_checksums({**h,'X-Checksum-SHA256':'a'*64},sha,md5)
        with self.assertRaises(ValueError):check_provider_checksums({'Digest':'unsupported=abc'},sha,md5)

    def test_completed_saved_archive_is_reused_without_request(self):
        b=b'PK synthetic';name=JOB['expected_archive_name']
        with tempfile.TemporaryDirectory() as root:
            Path(root,name).write_bytes(b)
            r={'name':name,'page_url':JOB['page_url'],'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
            atomic_json(Path(root,name+'.capture.json'),r)
            self.assertEqual(recover_file(root,JOB),r)

    def test_interrupted_rename_uses_persisted_exact_partial_bytes(self):
        b=b'PK synthetic';name=JOB['expected_archive_name']
        with tempfile.TemporaryDirectory() as root:
            Path(root,name+'.part').write_bytes(b)
            r={'name':name,'page_url':JOB['page_url'],'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
            atomic_json(Path(root,name+'.capture.json'),r)
            recover_file(root,JOB)
            self.assertEqual(Path(root,name).read_bytes(),b)
            self.assertFalse(Path(root,name+'.part').exists())

    def test_mutated_or_unattributed_capture_never_silently_refreshed(self):
        name=JOB['expected_archive_name']
        with tempfile.TemporaryDirectory() as root:
            Path(root,name).write_bytes(b'different')
            with self.assertRaises(ValueError):recover_file(root,JOB)
            atomic_json(Path(root,name+'.capture.json'),{'name':name,'page_url':JOB['page_url'],
                'bytes':9,'sha256':'a'*64})
            with self.assertRaises(ValueError):recover_file(root,JOB)


if __name__=='__main__':unittest.main()
